defaults:
  - override hydra/launcher: submitit_slurm

root: data
data: fire
diff: True

acc_sphere: True

train:
  lr: 1e-4
  itrs: 600000
  batch_size: 512

model:
  hidden_dim: 512
  n_hidden: 5
  t_steps: 0
  ema: 0.999
  harm: False
  harm_start: 6
  harm_end: 8
  scale_by_sigma: True
  act: silu

ssm: False
sigma_min: 0.001
sigma_max: 4
C: 12G


hydra:
  run:
    dir: /atlas2/u/aaronlou/exp_local/riem_diff_pp/earth/${data}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: /atlas2/u/aaronlou/exp/riem_diff_pp/earth/${data}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 10079
    partition: atlas
    account: atlas
    mem_gb: 16
    # exclude: atlas11,atlas15,atlas16,atlas17,atlas18
    cpus_per_task: 8
    gpus_per_node: 1
    constraint: ${C}