defaults:
  - override hydra/launcher: submitit_slurm

root: /atlas2/u/aaronlou/datasets/
#load_dir: /atlas2/u/aaronlou/exp/riem_diff_pp/ood/CIFAR-10/2023.05.13/034236/0
# load_dir: /atlas2/u/aaronlou/exp/riem_diff_pp/ood/CIFAR-100/2023.05.13/034217/0
load_dir: null
p: 0.05
exact_div: False

C: 24G



hydra:
  run:
    dir: /atlas2/u/aaronlou/exp/riem_diff_pp/ood/eval/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: /atlas2/u/aaronlou/exp/riem_diff_pp/ood/eval/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 10079
    partition: atlas
    account: atlas
    mem_gb: 32
    # exclude: atlas11,atlas15,atlas16,atlas17,atlas18
    cpus_per_task: 8
    gpus_per_node: 1
    constraint: ${C}